insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (1, 'vestibulum ante', false, 1);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (2, 'nulla', true, 1);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (3, 'molestie hendrerit', true, 1);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (4, 'pellentesque ultrices', false, 1);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (5, 'ligula', false, 2);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (6, 'sollicitudin ut suscipit', true, 2);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (7, 'turpis', false, 2);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (8, 'sit amet', false, 2);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (9, 'interdum', true, 3);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (10, 'nisl aenean lectus', false, 3);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (11, 'tellus in', false, 3);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (12, 'aenean', false, 3);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (13, 'elit sodales scelerisque', false, 4);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (14, 'in congue etiam', false, 4);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (15, 'praesent blandit lacinia', false, 4);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (16, 'sit', true, 4);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (17, 'volutpat erat', false, 5);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (18, 'morbi vestibulum velit', false, 5);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (19, 'vulputate nonummy', true, 5);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (20, 'donec vitae', false, 5);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (21, 'vitae consectetuer', false, 6);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (22, 'erat eros', true, 6);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (23, 'nullam varius', false, 6);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (24, 'nascetur ridiculus mus', false, 6);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (25, 'ante', false, 7);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (26, 'justo etiam', false, 7);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (27, 'ut rhoncus', false, 7);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (28, 'eros vestibulum', true, 7);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (29, 'at nulla suspendisse', false, 8);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (30, 'praesent blandit lacinia', false, 8);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (31, 'nisi', true, 8);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (32, 'lacinia erat vestibulum', true, 8);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (33, 'varius', false, 9);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (34, 'bibendum', true, 9);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (35, 'odio in', false, 9);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (36, 'pede', false, 9);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (37, 'justo', true, 10);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (38, 'ultrices aliquet maecenas', false, 10);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (39, 'vulputate vitae nisl', false, 10);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (40, 'sem mauris laoreet', false, 10);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (41, 'semper rutrum', false, 11);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (42, 'urna pretium nisl', false, 11);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (43, 'faucibus', false, 11);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (44, 'volutpat', true, 11);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (45, 'magna bibendum imperdiet', true, 12);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (46, 'semper', false, 12);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (47, 'sapien cursus vestibulum', false, 12);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (48, 'risus semper', false, 12);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (49, 'non', false, 13);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (50, 'erat quisque', false, 13);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (51, 'etiam faucibus', true, 13);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (52, 'amet', false, 13);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (53, 'leo odio porttitor', false, 14);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (54, 'nam dui', false, 14);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (55, 'velit vivamus', true, 14);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (56, 'viverra pede', false, 14);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (57, 'elementum ligula vehicula', false, 15);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (58, 'interdum', true, 15);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (59, 'massa id', false, 15);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (60, 'orci mauris', false, 15);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (61, 'amet eleifend', false, 16);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (62, 'iaculis congue', false, 16);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (63, 'eget eros', false, 16);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (64, 'odio donec vitae', true, 16);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (65, 'sed tristique in', false, 17);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (66, 'dui maecenas', false, 17);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (67, 'sapien', true, 17);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (68, 'quis augue luctus', false, 17);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (69, 'pretium', false, 18);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (70, 'ornare imperdiet', true, 18);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (71, 'nisl ut volutpat', false, 18);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (72, 'in hac habitasse', false, 18);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (73, 'libero', false, 19);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (74, 'vestibulum sed', true, 19);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (75, 'tortor quis turpis', true, 19);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (76, 'imperdiet et commodo', false, 19);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (77, 'elit proin', false, 20);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (78, 'odio', false, 20);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (79, 'leo maecenas', false, 20);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (80, 'lorem ipsum dolor', true, 20);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (81, 'mi pede malesuada', true, 21);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (82, 'at', false, 21);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (83, 'nam', false, 21);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (84, 'placerat ante nulla', false, 21);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (85, 'dui', false, 22);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (86, 'nec euismod scelerisque', false, 22);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (87, 'tincidunt ante vel', true, 22);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (88, 'justo etiam pretium', false, 22);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (89, 'venenatis tristique fusce', true, 23);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (90, 'iaculis', false, 23);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (91, 'curae donec', false, 23);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (92, 'a', false, 23);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (93, 'vestibulum', false, 24);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (94, 'tincidunt ante vel', false, 24);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (95, 'proin eu mi', false, 24);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (96, 'vel', true, 24);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (97, 'id massa', false, 25);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (98, 'sem', true, 25);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (99, 'volutpat dui maecenas', false, 25);
insert into question_choices (choice_id, choice_ans, is_right_choice, question_id) values (100, 'fusce consequat nulla', false, 25);
