insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (1, 'Marketing', true, 19);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (2, 'Human Resources', false, 10);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (3, 'Sales', false, 13);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (4, 'Services', true, 9);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (5, 'Accounting', true, 13);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (6, 'Support', true, 10);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (7, 'Services', false, 7);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (8, 'Sales', true, 10);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (9, 'Product Management', true, 9);
insert into QUIZ (quiz_id, quiz_name, is_active, teacher_id) values (10, 'Marketing', false, 19);
