insert into quiz_questions (question_id, question_title, quiz_id) values (1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into quiz_questions (question_id, question_title, quiz_id) values (2, 'Nunc rhoncus dui vel sem.', 2);
insert into quiz_questions (question_id, question_title, quiz_id) values (3, 'Duis consequat dui nec nisi volutpat eleifend.', 3);
insert into quiz_questions (question_id, question_title, quiz_id) values (4, 'Aliquam sit amet diam in magna bibendum imperdiet.', 4);
insert into quiz_questions (question_id, question_title, quiz_id) values (5, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 5);
insert into quiz_questions (question_id, question_title, quiz_id) values (6, 'Duis mattis egestas metus.', 1);
insert into quiz_questions (question_id, question_title, quiz_id) values (7, 'Ut tellus.', 2);
insert into quiz_questions (question_id, question_title, quiz_id) values (8, 'Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into quiz_questions (question_id, question_title, quiz_id) values (9, 'Proin risus.', 4);
insert into quiz_questions (question_id, question_title, quiz_id) values (10, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 5);
insert into quiz_questions (question_id, question_title, quiz_id) values (11, 'Nullam porttitor lacus at turpis.', 1);
insert into quiz_questions (question_id, question_title, quiz_id) values (12, 'In quis justo.', 2);
insert into quiz_questions (question_id, question_title, quiz_id) values (13, 'Aliquam non mauris.', 3);
insert into quiz_questions (question_id, question_title, quiz_id) values (14, 'Cras non velit nec nisi vulputate nonummy.', 4);
insert into quiz_questions (question_id, question_title, quiz_id) values (15, 'Phasellus in felis.', 5);
insert into quiz_questions (question_id, question_title, quiz_id) values (16, 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
insert into quiz_questions (question_id, question_title, quiz_id) values (17, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2);
insert into quiz_questions (question_id, question_title, quiz_id) values (18, 'Proin interdum mauris non ligula pellentesque ultrices.', 3);
insert into quiz_questions (question_id, question_title, quiz_id) values (19, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 4);
insert into quiz_questions (question_id, question_title, quiz_id) values (20, 'In hac habitasse platea dictumst.', 5);
insert into quiz_questions (question_id, question_title, quiz_id) values (21, 'Vestibulum ac est lacinia nisi venenatis tristique.', 1);
insert into quiz_questions (question_id, question_title, quiz_id) values (22, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 2);
insert into quiz_questions (question_id, question_title, quiz_id) values (23, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 3);
insert into quiz_questions (question_id, question_title, quiz_id) values (24, 'Nunc nisl.', 4);
insert into quiz_questions (question_id, question_title, quiz_id) values (25, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 5);
